print("hello M.6/14")
print("My nanme is Natthajak Sisensui")
print("My nick name is Aomsin")
print("I am 17 years old")
print("I study at Chonrasadornumrung")
print("I live in Chonburi")
print("My favorite color is Black")
print("My favorite food is Pad kra pao")
print("My favorite subject is Math")
print("My birthday is 17th March 2005")
print("I hate Science")
# ชื่อ ณัฐจักขณ์ สีเสนซุย เลขที่25